title: The Ace of Spades and Other Devilish Tales
author: Tony Hirst
copyright: "2024"

only_build_toc_files: true

execute:
  execute_notebooks: force
  timeout: 60  
parse:
  myst_dmath_double_inline: true

sphinx:
  config:
    html_copy_source: false

